//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibFinanceDummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetailInfo
    {
        public int Std_Other_Info_ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Std_Father_Name { get; set; }
        public string Std_Mother_Name { get; set; }
        public string Std_Phone { get; set; }
        public string Std_Gender { get; set; }
        public string Std_BloodGroup { get; set; }
    }
}
