// <auto-generated />
namespace TibFinanceDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class artistandalbumtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(artistandalbumtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202310090945498_artist and album table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
