// <auto-generated />
namespace TibFinanceDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class moduleandmenudatatableschemaupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moduleandmenudatatableschemaupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202309211306324_module and menu datatable schema update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
