// <auto-generated />
namespace TibFinanceDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class userpermissiontablechangedavariable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userpermissiontablechangedavariable));
        
        string IMigrationMetadata.Id
        {
            get { return "202309251249146_user permission table changed a variable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
